name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  path_provider: ^2.0.11

  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0

  file_picker: ^5.2.2
  fb2_parse: ^1.0.1
  webview_flutter: ^4.0.1
  flutter_bloc: ^8.1.1
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.9
  routemaster: ^1.0.1
  #google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_lints: ^2.0.0
  

fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400

flutter:

  uses-material-design: true

  assets:
    - assets/images/BookVector.png
    - assets/images/StarVector.png
    - assets/images/SettingsVector.png
    - assets/settings.json
